@startuml

class Publicacion {
-nombre:string
}
class Usuario {
-nombre:string
}
class Estudiante extends Usuario{

}
class Docente extends Usuario{

}
class Egresado extends Usuario{

}
class Grupo {
-nombre:string
}
class Comentario {
-comentario:string
}

Comentario "1" -- "*" Publicacion : corresponde
Usuario "1" -- "*" Usuario : sigue
Usuario "1" -- "*" Comentario : realiza
Usuario "1" -- "*" Grupo : pertenece
Usuario "1" -- "*" Publicacion : crea

@enduml