@startuml

class Publicacion {
-comentario:Comentario
-nombre:string
+publicar(comentario):void
}
class Usuario {
-usuario:Usuario
-nombre:string
+seguirUsuario(usuario):void
}
class Estudiante extends Usuario{

}
class Docente extends Usuario{

}
class Egresado extends Usuario{

}
class Grupo {
-usuario:Usuario
-nombre:string
+unirUsuario(usuario):void
}
class Comentario {
-usuario:Usuario
-comentario:string
+comentar(comentario):void
}

Comentario "1" -- "*" Publicacion : corresponde
Usuario "1" -- "*" Usuario : sigue
Usuario "1" -- "*" Comentario : realiza
Usuario "1" -- "*" Grupo : pertenece
Usuario "1" -- "*" Publicacion : crea

@enduml